package exceptionhandling;

public class Example3 {
	public static void main(String[] args) {
		try {
			int result = 10 / 2; // This will not throw an exception
			System.out.println("Result: " + result);
		} catch (ArithmeticException e) {
			System.out.println("Caught an exception: " + e.getMessage());
		} finally {
			System.out.println("This is the finally block, always executed.");
		}
		System.out.println("Program continues...");
	}
}
